name: Output Information
on:
  workflow_dispatch:
    inputs:
      branch:
        description: name of the target branch
        required: true
        default: master
jobs:
  info:
    runs-on: ubuntu:latest
    steps:
      - name: Output Github Content
        run: echo "${{ toJSON(github) }}"